# Generated by Django 3.2.6 on 2021-09-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='课程名称')),
                ('desc', models.TextField(verbose_name='课程目标')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='课名称')),
                ('program', models.BooleanField(verbose_name='程序')),
                ('sprites', models.BooleanField(verbose_name='素材')),
                ('plan', models.BooleanField(verbose_name='大纲')),
                ('ppt', models.BooleanField()),
                ('knowledge', models.TextField(verbose_name='知识点')),
                ('game', models.BooleanField(verbose_name='教具/游戏')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
