# Generated by Django 3.2.6 on 2021-09-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Lecture',
        ),
    ]
