# Generated by Django 3.2.6 on 2021-09-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210919_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='level',
            new_name='course',
        ),
    ]
